name: instabug_flutter_modular
description: An add-on for the Instabug Flutter SDK that provides screen loading support for Flutter Modular v5.
version: 0.0.1
homepage: https://www.instabug.com

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  flutter_modular: '>=5.0.0 <6.0.0'
  instabug_flutter:
    # TODO: Change Git to the package on Pub once manual screen loading support is out in the official SDK.
    git:
      url: git@github.com:Instabug/instabug-flutter.git
      ref: snapshot/feat/support-manual-screen-loading-end-screen-loading


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
