version: 2
jobs:
   test:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.19.0
      
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
      - run: flutter analyze .
      - run: flutter pub publish --dry-run
      
   release:
     docker:
      - image: ghcr.io/cirruslabs/flutter:latest
     steps:
      - checkout
      - run: ./release.sh

workflows:
  version: 2
  build-test:
    jobs:
      - test
      - hold_release:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: main
      - release:
          requires:
            - hold_release
          filters:
            branches:
              only: main
